print(' ------------------------------------------------ ')
print('|                                                |')
print('|    01HelloWorld                                |')
print('|    Name : Alicia Rodrigues                     |')
print('|    Version : 01                                |')  
print('|                                                |')
print(' ------------------------------------------------ ')
